spring:
  datasource:
    url: jdbc:mysql://192.168.1.3:3306/rentDB?createDatabaseIfNotExist=true
    username: hp
    password: n11nUjKIgTa7ROf8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



